### ISSUE TITLE
MockStorageInstance

### ISSUE THREAD

**Issue by mprobst** [angular/clutz#224]
```
Class 'MockStorage_Instance' incorrectly implements interface 'Storage'.
  Index signature is missing in type 'MockStorage_Instance'.
```

**Comment by rkirov** [comment]
We try to be clever and reuse lib.d.ts Storage, but Closure's Storage diverges from lib.d.ts storage. Closure's 'Storage' doesn't have index signature (no way to even express that in closure AFAIK). But when we swap with TS Storage, MockStorage does not implement the interface any longer.

My proposed fix is detach closure types from TS types completely, even for platfom APIs, because as you see here, there are too many incompatible ways to type a platform API.

**Comment by mprobst** [comment]
Completely detaching the platform APIs sounds like it could be a lot of
work, and lead to fragmentation - we'd have Closure APIs not necessarily
agreeing with what lib.d.ts proclaims. For compilation, we also have to
make sure Closure understands when code implements an external interface,
otherwise we risk Closure mangling all the external symbols. And last but
not least we don't currently have a way to communicate to Closure that
lib.d.ts is an extern, i.e. we cannot go from .d.ts to an externs file.

I agree that having two sets of platform APIs and hoping that we can make
them match is kind of crazy, but given these other difficulties, it might
be the lesser evil. Is there a more short term fix we can chose?

I think the equivalent of an index signature in Closure should be extending
`Object<T>` and putting @dict on the object, right?

Rado Kirov <notifications@github.com> schrieb am Do., 18. Feb. 2016 um
03:58 Uhr:

**Comment by rkirov** [comment]
Agree, having the platform APIs typed twice in the same compilation unit is trouble. So is swapping the platform API types underneath closure code that has been written to work with them.

Issues with closures' minification pass seem orthogonal to the discussion at hand. For example, any code that relies on lib.d.ts's File.msClose property is broken because Closures' File interface does not have that property, irrelevant of what clutz does. If anything that points towards not using lib.d.ts at all and using clutz's generated definitions ones, which this PR attempts to do.

Check out the longer doc, I am going to send to the team.

**Comment by rkirov** [comment]
Final solution - modify lib.d.ts to match closure's type shape. Only differences detected were Blob and Storage APIs.
