### ISSUE TITLE
Support variables named like reserved keywords

### ISSUE THREAD

**Issue by rehmsen** [angular/clutz#270]
I encountered this when trying to use Clutz on _ng.material.components.switch_. The *.d.ts produced by Clutz contains:

```
declare namespace ಠ_ಠ.clutz.ng.material.components {
  var switch : any;
}
```

And then the Typescript compiler throws

> java/com/google/developers/console/web/crash/common/_common_ts_js_typings.d.ts:155302:7: Variable declaration expected.

**Comment by rkirov** [comment]
This one is going to be tricky. If we rename it, it won't compile with closure. `namespace foo.switch` is also disallowed by TS. 

For now I can remove the emit (or even better emit a comment), and expect users to lie to the typesystem `(components as any).switch`. Any better ideas?

I can ask material folks to rename that api, but material 1.5 is widely used already.
The moral of the story is that `switch`, `for` are probably not good names for external apis :)

**Comment by mprobst** [comment]
The observation here is that it's legal in JavaScript (ES5+) to use a keyword as a property name in an object literal or class, but not as a sole variable name.

```js
class Foo {
  switch() { ... } // legit
}

var switch = ...; // nope
```

Can we restructure our way of providing these such that "switch" will be a property of an object instead of a standalone variable?

**Comment by rkirov** [comment]
Its tricky. The only object switch truly belongs to is `components`, so that leads to:

```
declare namespace ಠ_ಠ.clutz.ng.material {
  var components : {switch: any};
}
```

which will collide with any other 'material.components.foo' namespace. So now we just forced all components to live in `var components : {switch: any, foo: any, bar : any }`. The good news is that we can still export the correct module definitions as:

```
declare module 'goog:ng.material.switch' {
  import alias = ಠ_ಠ.clutz.ng.material.switch;
  export default alias;
}
```

so the problem is only scoped to our tool.

Note that 
```
import {switch} from '...'
```
is also wrong, so the import site will have to rename.
