### ISSUE TITLE
Clutz chokes on doubly recursive typedefs

### ISSUE THREAD

**Issue by rkirov** [angular/clutz#286]
For example the following, throws clutz into an infinite loop

```javascript
/**
 * @typedef {{
 *   arr: (rec.ns.Arr),
 * }}
 */
rec.ns.El;

/**
 * @typedef { Array.<rec.ns.El> }
 */
rec.ns.Arr;
```

**Comment by jjudd** [comment]
This is still happening. Interestingly, the test passes, but running it on the test case or the case below outside of the test framework causes an infinite loop.

```JavaScript
/**
 * @typedef {{
 *  't': Toast
 * }}
 */
var Waffle;

/**
 * @typedef {{
 *  'w': Object.<Waffle>
 * }}
 */
var Toast;
```
To reproduce, run clutz on an empty js file with the above example as an extern and it goes into an infinite loop.

I spent some time looking into this. It occurs because `typedefs` is a HashMap of JSType -> String. The hashCode function on JSType  is the default hashCode function, i.e., it returns a different HashCode for two different instances of the same JSType. 

```Java
  @Override
  public int hashCode() {
    return System.identityHashCode(this);
  }
```

To get around this, we can change the HashMap to compare the output of toString for the JSType or change data structures and use `.equals()`, which has been implemented for JSType. This fixes the simple example above.

That is not the only problem, though. When I run clutz on our codebase with the above fix applied it still enters an infinite loop.

Clutz encounters a doubly recursive type that is provided as the parameter for a function, e.g., 
```JavaScript
/*
 * @param {!Array.<string>} ids
 * @return {!Toast}
 */
lucid.foo.prototype.getBar = function(ids)
```
The typedef for `Toast` is not yet in the `typedefs` map. Accordingly, clutz attempts to unroll the `Toast` type forever.

What mechanism is supposed to ensure that a type is in the `typedefs` map by the time we encounter it being used in the code?

Also, I see this comment in the clutz code that hints at a strategy to actually fix this. I'm not super familiar with the closure codebase, but am actively working on this. Would you be willing to point me in the right direction?

```
 * Maps types to names for all emitted typedefs, so that further type walks just use the name.
   *
   * This is a reverse subset of the private map namesToTypes that Closure keeps in TypeRegistry.
   * TODO(rado): Try to extract that info in a single pass, instead of rebuilding it.
```

**Comment by jjudd** [comment]
I did not see that ac92bfe6c8edf9516d21c30f34330e15ce13750f had been committed. Quickly trying it out now.

**Comment by jjudd** [comment]
Ran the new code with my simple example above. I see neither of the typedefs included in the `typedefs` map after the preprocessing step. Accordingly, the infinite loop still happens. Trying to figure out why.

**Comment by jjudd** [comment]
Just figured out that my above example is invalid. Assigning the typedefs to vars is what broke things :) Changing it to be correct made things work.

```JavaScript
var foo = {};

/**
 * @typedef {{
 *  't': foo.Toast
 * }}
 */
foo.Waffle;

/**
 * @typedef {{
 *  'w': Object.<foo.Waffle>
 * }}
 */
foo.Toast;
```

**Comment by rkirov** [comment]
Hi James, (I think you are the first non-googler using Clutz, so you get a personal greeting :))

Indeed I was hoping that ac92bfe fixed your second problem and it sounds like it did, except the odd 'var typedef' case. Do you mind filing a separate issue just for that. It sounds like a mix between odd closure behavior and a bug in the typedef collection and expansion code.

About the first issue, relying on hashCode is indeed very dodgy. At the same time implementing proper type comparison would mean all types of the same shape will get renamed during emit. For example:
```
/** @typedef {{foo: string}} */ Foo
/** @const {{foo: string}} */ a; 
or 
/** @typedef {{foo: string}} */ Bar
/** @const {Bar} */ b;
```
If we do the type equality expansion, both will be emitted as 'a: Foo' and 'b: Foo' (or Bar, or whatever sticks last in the hash map). Currently, because of the way closure produces actual type objects, the emits better (only Foo references will be replaced). The downside is of course, that we rely on a Closure compile implementation detail.

In all honesty the best solution would be if closure had an API to visitType while keeping the typedef names.

So for the time being, I want to evaluate the downsides of both approaches. Are you still stuck?

**Comment by jjudd** [comment]
Hi Rado! Thanks for the greeting. Over at Lucidchart, we're working on introducing TypeScript into our codebase using Tsickle and Clutz. Our existing codebase has several hundred thousand lines of Closure compiled js, so it's been exciting. 

Your commit does seem to have eliminated the infinite loop we were getting stuck in. Thanks for that. We are no longer stuck :)

As for how to determine type equivalence, what you say makes sense. It would be best if TypeScript had an API to visitType with the typedef names. That way, name equivalence could be checked, and everything should work. I wonder if it is possible to go the equality route and somehow declare all structurally equivalent types equal in the definition file.

In your example above, the definition file might look something like

```TypeScript
type Foo: {foo: string};
type Bar = Foo;

a: Foo
b: Foo
```

I'm not sure what repercussions that might have, though. Regardless, what you committed seems to work for now, which is what matters.
