### ISSUE TITLE
Gents should output lint-able code

### ISSUE THREAD

**Issue by voithos** [angular/clutz#317]
In addition to formatting the emitted TypeScript (#309), gents should also avoid generating code that has lint errors. For example, `var` should be avoided in favor of `let` or `const`. Ideally, the generated code could be piped into e.g. tslint, without reporting any errors.

**Comment by gmoothart** [comment]
Closing since the specific case mentioned (var/let) has been handled. Some lint errors shouldn't be handled by gents (adding a default case to a switch statement) and others (removing underscores from private fields) seem best left to a post-processing step or human inspection.

Other specific examples can be added as their own bug.
