### ISSUE TITLE
Files with same basename clobber each other

### ISSUE THREAD

**Issue by ewinslow** [angular/clutz#348]
a/service.js
b/service.js

will convert to

a/service.ts
b/service.ts

Except that the output from converting one of the files will be the same between both `.ts` outputs, losing information from the other `.js` file.

**Comment by gmoothart** [comment]
:cry:

**Comment by ewinslow** [comment]
Pretty sure this is the culprit:

https://github.com/angular/clutz/blob/ad623524ca1b1a4a550922820dae7a33b53da96a/src/main/java/com/google/javascript/gents/TypeScriptGenerator.java#L193

Trying my hand at submitting a PR here...

**Comment by ewinslow** [comment]
I'm not familiar enough with Java APIs to be productive on this, unfortunately so it's on hold for now while I do other stuff. Don't be afraid to pick it up if you're motivated...

**Comment by gmoothart** [comment]
@mprobst I am a little stuck on this one. I think Evan is right that the culprit is [here](https://github.com/angular/clutz/blob/ad623524ca1b1a4a550922820dae7a33b53da96a/src/main/java/com/google/javascript/gents/TypeScriptGenerator.java#L193). The obvious solution is to use full paths as the hash keys. But the Node file objects only have a #getSourceFileName method; I can't find an api for returning the whole path. Suggestions?

**Comment by mprobst** [comment]
I thin the problem is that we explicitly get the file name w/o extension
here, right?

https://github.com/angular/clutz/blob/ad623524ca1b1a4a550922820dae7a33b53da96a/src/main/java/com/google/javascript/gents/TypeScriptGenerator.java#L112

According to JavaDoc, the path returned by `getSourceFileName` (and the
static source file underneath) are unique across the compilation, so I'd
assume they include the full paht.

Gabe Moothart <notifications@github.com> schrieb am Fr., 30. Sep. 2016 um
17:25 Uhr:
