### ISSUE TITLE
A lack of documentation 😕

### ISSUE THREAD

**Issue by lhecker** [angular/clutz#420]
Hey!

First of all: Thanks for the project!

The problem I'm now facing though is that due to a lack of documentation I can't for the life of me figure out how to properly use this tool. And it's not like I've tried: I have _successfully_ generated a d.ts file from a simple protobuf project, by using something like this:

```
./clutz \
    --externs es3.js \
    --externs es6.js \
    --externs ... \
    my_generated_protobuf_code.js \
    > out.d.ts
```

where `es{3,6}.js` are the externs files from the [closure compiler](https://github.com/google/closure-compiler/tree/master/externs). Here I already faced my first problem: It took me ages to figure out how to solve the e.g. `Array is undeclared` errors! I actually thought that including the `es6_min.js` file in this project would be enough to solve it, because that's how the current readme made it sound like. In hindsight it's of course very much obvious that you have to use the proper files from the closure compiler, but back then it wasn't.

What I still haven't solved is the fact that the generated .d.ts file is a whopping 540kB, which is funny because my .js file in comparison is only something like 30 kB. The reason for that is that clutz is including **everything** without doing a dependency analysis and thus also includes the entirety of all externs in the output (e.g. es3/es6 stuff which is huge).

I tried using `--depgraphs` because #102 made it sound like it could be used to trim out unneeded code, but then I noticed I can't call `./clutz --depgraphs file > out` because for some reason I still have to provide a input file and nowhere I can read up on how to use this feature or how it works, without reading through all the Java code. 😕

Due to that I want to kindly ask the maintainers of this project to please write up some documentation - even if it would only be a short one. I'm sure future users of clutz would really appreciate this. 🙂

**Edit:** I just found #297. That would already kinda solve the "540kB problem".

**Comment by rkirov** [comment]
Hello :)

Sorry for the frustration you have experienced. Clutz fits within a niche of Google internal tools, and even though they are all open source, a lot of knowledge on how to use them and most importantly examples are kept inside google's internal repos. On top of it, we haven't had much external usage to justify expanding on the documentation. So thanks for speaking up, otherwise I wouldn't even know that there is in external interest :)

More practically can you review https://github.com/angular/clutz/pull/423?

About the size of the generated d.ts file, I don't think it is a big of a problem as it sounds. Usually, we feed through clutz a quite large chuck of closure (like most of the closure library) so the fixed overhead is dwarfed by it. Also no part of the .d.ts makes it past the TS emit to js, so it doesn't affect your js binary size. 

Maybe you are trying to check in the generated .d.ts and that causes concerns for having such a large file. Note that we run clutz as part of our build and never check in the generated d.ts, which leads to a number of decisions. For example, the current output prefers keeping preserving semantics right than being human readable or concise.

Finally, we already fixed issue #297, but only (as you noticed) if you pass a .depsgraph file. Depgraphs is tied to a fileformat produced by some internal build tool (something like https://bazel.build/). If your build tool doesn't output a depsgraph, I dont want to make you write it just for clutz. I rather have an extra flag to clutz (--roots) that does the same thing without the depsgraph. How does that sound for your usecase?

**Comment by lhecker** [comment]
Hey @rkirov, thanks for your reply!

> Clutz fits within a niche of Google internal tools

Yeah I thought so already. Many people use TypeScript for (browser) frontend development nowadays. Furthermore gRPC will be coming to the browser sooner or later and Protobuf is also slowly gaining popularity with web devs. So I believe you might see a uptake of interest in this tool in the future.

> About the size of the generated d.ts file, I don't think it is a big of a problem as it sounds.
> [...]
> Maybe you are trying to check in the generated .d.ts and that causes concerns for having such a large file.

Yeah exactly. Since the generated protobuf "classes" are the only Closure-style JS code I have in my project (with the rest being TypeScript & ES6/CommonJS) I thought it might be easier if I check in the "protobuf.js" and "protobuf.d.ts" files as binary blobs in the repo. Maybe you're right though and setting up a dev chain which generates the necessary files up-to-date only during the actual build might be a better idea.

> I rather have an extra flag to clutz (--roots) that does the same thing without the depsgraph. How does that sound for your usecase?

That would be quite awesome! Especially if it's not too hard to implement it would be a very welcome change. 🙂 Apart from `roots` you could also call it something like `filter` though. That filter could work similar to `WHERE type_name LIKE ':filter%'` if you know what I mean.

**Comment by rkirov** [comment]
We took a stab at improving this. There are a lot more things to be done, but I am closing this bug in favor of more narrowly scoped ones (pls file such).
