### ISSUE TITLE
closure infers types of overriden methods, but TS implies 'any'

### ISSUE THREAD

**Issue by rkirov** [angular/clutz#452]
For example:

```javascript
class X {
  /** @param {string} a */
  foo(a) {}
}

class Y extends X {
  /** @override */
  foo(a) {}
}

const a = new Y().foo(0);
```
works fine in closure (type error on the passing 0)

we emit
```javascript
class X {
  foo(a: string) {}
}

class Y extends X {
  foo(a) {}
}
```

which triggers `noImplicitAny` error, thus slowing down the conversion. Can we use the inheritance chain to grab the original type signatures and reemit?

**Comment by dpurp** [comment]
Note: We don't use Closure Type Inference in gents because it doesn't (didn't ?) work with ES6 output.

**Comment by rkirov** [comment]
Would a syntactic resolution of the inheritance chain work? I.e. find `extends`, resolve symbol `X`, find `foo` declaration use `@param` nodes?

**Comment by mprobst** [comment]
The problem is that Closure cannot type check without down-transpiling from
ES6 to ES5, which would break other things. What we could try is have one
Closure pass type check, and another just parse, and then look up symbols
by their name (`module.Y.foo`) in the symbol table of the type checking
pass, while converting the source from the parse-only pass.

**Comment by rkirov** [comment]
We fixed this issue in a TSLint post-gents pass.
