### ISSUE TITLE
gents should remove `goog.module.declareLegacyNamespace`

### ISSUE THREAD

**Issue by rkirov** [angular/clutz#558]
Since it is hard to gents to properly infer whether those are currently needed or not, one option is to go with the heuristic that they are most likely not, and people can add them back manually when needed.

**Comment by iteriani** [comment]
The historical context for goog.module.declareLegacyNamespace is as such:

Problem:
It is difficult to migrate a traditional Closure file to a goog.module if that file is used by existing goog.provide’d files.  All such dependents must be updated to use goog.module.get or intermediate file must be introduced to “translate” the module exports.

Proposal:
Introduce “goog.module.declareLegacyNamespace”.  This method when called from a goog.module would perform the equivalent of a goog.provide of the namespace.

In this case though, they are migrating to TypeScript anyways, which is difficult in and of itself since they have to update call sites, as the namespace has changed. While they are there, they can use goog.module.get.

**Comment by rkirov** [comment]
We remove this in postprocessing, because it is so easy to do. No point adding it to gents.
