### ISSUE TITLE
Avoid emitting for unannotated @override

### ISSUE THREAD

**Issue by evmar** [angular/clutz#597]
JS code does:

```js
MyClass.prototype.method = goog.abstractMethod;
```

Clutz infers:

```ts
  method: any;
```

TS code does:

```ts
class X implements MyClass {
  method(...) {}
```

Now compile fails with `Class 'X' defines instance member property 'method', but extended class 'MyClass' defines it as instance member function.`

Potential workarounds:
- special case goog.abstractMethod to treat as function not property
- TS code can treat method as a member, not a method

**Comment by rkirov** [comment]
one more hack: pass `base.js` to every clutz run, but don't emit anything from it.

**Comment by evmar** [comment]
I think even if we had base.js around with a full type for `goog.abstractMethod`, there is no type we could give to `MyClass.method` that would allow subclasses to override it.

**Comment by rkirov** [comment]
Why is not `method(...args:any[]): any` acceptable for "that would allow subclasses to override it." I think that is what we currently do and it does work.

Now we need a way to identify 'prototype fields' that are 'likely to be methods'. (Also I just realized that prototype fields is not something expressible in ES6 classes, which is why we emit them as instance fields, but they are subtly different).

Since clutz is type-driven, it is not easy to see the original AST that produced the property 'method' and the type 'any'. But Lucas, just recently added some AST preprocessing, so we can use that pass to detect 'goog.abstractMethod' .

Alternatively, we can compile with 'base.js' or even with a smaller shim that just contains 'goog.abstractMethod' definition.

The code for emitting the prototype props is here :
https://github.com/angular/clutz/blob/master/src/main/java/com/google/javascript/clutz/DeclarationGenerator.java#L2156

Also, notice there that we take special care to collect super class fields and consistently emit to avoid field/method issue:

https://github.com/angular/clutz/blob/master/src/main/java/com/google/javascript/clutz/DeclarationGenerator.java#L2157

Potentially, there will be more regressions here, because methods like 'getSuperClassFields' cannot succeed in the partial sources.

**Comment by evmar** [comment]
Dup of #552.
