### ISSUE TITLE
Incremental clutz doesn't reuse TS library-defined types

### ISSUE THREAD

**Issue by evmar** [angular/clutz#598]
JS:

```js
/** @return {!Node} */
function foo() { ... }
```

Typings:

```js
function foo() : ಠ_ಠ.clutz.Node ;
```

`Node` is defined in the standard platform externs, so clutz doesn't emit a definition for `ಠ_ಠ.clutz.Node`.  Instead we should generate `: Node` in the typings.

**Comment by rkirov** [comment]
We always emit `ಠ_ಠ.clutz.T` when we see and unknown type that was written as 'T'.

https://github.com/angular/clutz/blob/4ccbc8c4349c66d97f599518c2fad02dc2de1e9b/src/main/java/com/google/javascript/clutz/DeclarationGenerator.java#L1778

Now the options are:
1) Relax the emit to just 'T', because of how namespaces work in Ts this is valid, missing types are looked up in parent namespaces

```typescript
declare namespace foo {
  interface I {}
}
namespace foo.bar {
  let x: I;
}
```

2) Always pass in platform externs even for incremental clutz, but don't emit their symbols.

I am leaning towards 1) which should be as simple as removing a prefix, but not sure what else will break then. Option 2) sounds too similar to the thing we talked about but so far decided against doing which is to pass transitive closure of sources to clutz but just emit for direct sources.

**Comment by rkirov** [comment]
Another place were we pick up the absolute name - https://github.com/angular/clutz/blob/4ccbc8c4349c66d97f599518c2fad02dc2de1e9b/src/main/java/com/google/javascript/clutz/DeclarationGenerator.java#L2731

**Comment by evmar** [comment]
I like the relaxed idea, we should try it and see how bad it is.  Do you know why we use the absolute name in the code you linked?

**Comment by rkirov** [comment]
When we have a global view, we can effectively statically know where each symbol comes from, so it is easier for debugging to output the fully qualified path, and not rely on TS to figure those out. That's just a slight preference I have had when touching that code, not sure we have consistently followed that though.

**Comment by rkirov** [comment]
fixed with - https://github.com/angular/clutz/commit/9303d0c468d3fbcad557259e6ccab3ec694dc6d9
